### PR TITLE
Plumb config

### LINKED ISSUE #190: Consolidate all environment variable fetching at the top of the stack
I was figuring out how to deploy Olympus and it was pretty hard to find all the env vars it uses, and which of those it requires. It'll be easier when we have docs but even then it's nicer to have things in one place.

Everything uses `envy.Get` or `envy.MustGet`, so we need to:

1. Move all those commands to the top of the stack (i.e. near the `main`)
2. ... possibly create a utility function to get all the env vars (consider using [envconfig](https://github.com/kelseyhightower/envconfig) instead of envy for consolidating)
3. Pass env vars down the stack

### PR DESCRIPTION
**Pull request by rchakra3**
This PR is a continuation of #453 

It should resolve #190, #284 and to some extent #261. I've plumbed timeouts through wherever implemented.

Files that are deleted in this PR are due to changes being made in #511 and #513 (Removing pop from storage and removing olympus as a storage implementation), so ideally this should be merged only after those changes have been approved and merged.

### CODE REVIEW

**Comment by rchakra3** [comment]
Also resolving conflicts in this PR is going to be SUPER annoying :) I'll probably do a squash and rebase after reviews

**Comment by robjloranger** [comment]
Might i suggest a squash and rebase first? That way we can start clean now that the config file PR is done.

**Comment by rchakra3** [comment]
Working on this today. I'll attempt a squash + rebase but there are so many conflicts I might just start afresh.

**Comment by rchakra3** [comment]
@robjloranger @michalpristas closing this in favor of #627 . There were simply too many merge conflicts. 

This also forced me to get caught up with the latest changes :)

**Pull request closed without merging**
