### PR TITLE
Override service account

### PR DESCRIPTION
**Pull request by bnrjee**
## What is the problem I am trying to address?
Describe the issue you have been trying to solve.
Athens chart uses the default service account and does not allow overriding it at the time of installation. This pr allows overriding service account name while installing athens with helm chart.
## How is the fix applied?

Mention briefly how you have applied the fix.
This fix will allow providing a service account name at the time of installation. Also the default name will be changed from "default" to "".

### CODE REVIEW

**Comment by gw0** [comment]
Duplicate of https://github.com/gomods/athens/pull/1672?

**Comment by arschles** [comment]
Yes, I've just reviewed and merged #1672. I am going to close this PR, so @bnrjee please let me know if you believe that this implements something that the other PR does not and we can reopen.

**Comment by bnrjee** [comment]
> Yes, I've just reviewed and merged #1672. I am going to close this PR, so @bnrjee please let me know if you believe that this implements something that the other PR does not and we can reopen.

With #1672, I do not see an option to keep a service account if it is already present and reuse it later. With the existing code, a service account is created with chart installation, and then removed when the chart is deleted. I am trying to create a service account by myself and use it to install this helm chart, which I believe is not possible with the existing code.

**Comment by bnrjee** [comment]
> Yes, I've just reviewed and merged #1672. I am going to close this PR, so @bnrjee please let me know if you believe that this implements something that the other PR does not and we can reopen.
@arschles ,
With the aforementioned requirements, let me know if this PR should be reopened or should I create a new one?

**Comment by arschles** [comment]
@bnrjee I see the difference now. Would you mind rebasing off of the current `main` branch now that #1672 is merged and submitting a new PR with your functionality?

**Comment by bnrjee** [comment]
> @bnrjee I see the difference now. Would you mind rebasing off of the current `main` branch now that #1672 is merged and submitting a new PR with your functionality?

I have created a new PR.
https://github.com/gomods/athens/pull/1677

**Comment by arschles** [comment]
Thanks @bnrjee. I'll check that one out today.

**Comment by bnrjee** [comment]
> Thanks @bnrjee. I'll check that one out today.

@arschles 
Did you get a chance to look into the changes?

**Comment by arschles** [comment]
Yup, just left some feedback.

**Pull request closed without merging**
