### PR TITLE
Correct issue with continuation token failures on deploy

### PR DESCRIPTION
**Pull request by chriscoffee**
**What is the problem I am trying to address?**

Between RELEASE.2019-09-26T19-42-35Z and RELEASE.2019-10-02T21-19-38Z
there's an issue with continuation tokens that's caused #1414 and #1413
to fail.

**How is the fix applied?**

Locked down version of minio to the one 9 days ago.

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes failures in the following PRs, but does not close them. #1413, #1414

### CODE REVIEW

**Comment by chriscoffee** [comment]
> LGTM but any idea why it started failing? Should we be updating our minio client/code in any way?

I left some notes in maintainers chat, for visibility:

**Comment by chriscoffee** [comment]
Changed the ticket slightly and tried to hunt down the problem in-amongst doing Cassandra things at work rather than just locking version numbers down.

I've upgraded `minio/minio-go` and disabled `testCatalog` for now but breakpoint of issue seems to be here and subsequent tests:

https://github.com/gomods/athens/blob/0f3ec263bc8750446ae19919ce20975995f14dd8/pkg/storage/compliance/tests.go#L232

I can probably pick this up later but I've got to go out for a bit. If anyone wants to pick this up feel free, hopefully you'll see the problem straight away

**Comment by marwan-at-work** [comment]
Merging for now to unblock others, but will try my best to get to the testCatalog problem soon.

**Comment by chriscoffee** [comment]
@marwan-at-work cheers! Sorry I got distracted with other things 😢

**Comment by arschles** [comment]
@chriscoffee you fixed the build on one of the PRs I had open, so a late :100: and thank you from me

**Pull request merged**
