### PR TITLE
Azureblob tests + checker fix

### LINKED ISSUE #1243: Fix Azure storage checker
**Describe the bug**
We check modules in v0.4.0 based on prefixes not based on explicit paths, so when two Versions have the same prefix, we get into trouble.
More on that here: https://github.com/gomods/athens/issues/1219#issuecomment-494973122

There's already a fix for s3 (thanks @marwan-at-work) but we need to do the same for Azure storage.

**To Reproduce**
Described here https://github.com/gomods/athens/issues/1219#issuecomment-494900010

**Environment (please complete the following information):**
 - OS: [e.g. Linux 64bit]
 - Go version :
 - Proxy version : v0.4.0
 - Storage (fs/mongodb/s3 etc.) :

**Additional context**
https://github.com/gomods/athens/issues/1219

### PR DESCRIPTION
**Pull request by marpio**
**What is the problem I am trying to address?**

Described in #1243 
We were also missing tests for azure blob storage.

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #1243

### CODE REVIEW

**Comment by marwan-at-work** [comment]
@arschles I'm not too savvy with Azure Blobs, but can you take a look and hit the merge button if all good? Thanks!

**Comment by arschles** [comment]
@marwan-at-work @marpio I think we should definitely hook up the tests to Azure. I'll set this up now

**Comment by arschles** [comment]
Ok, I've added `ATHENS_AZURE_ACCOUNT_KEY` and `ATHENS_AZURE_ACCOUNT_NAME` to the drone env (turned on for PRs 😱!). I believe future builds should be running the azure tests. Did I miss anything @marpio @marwan-at-work ?

**Comment by marwan-at-work** [comment]
@arschles I'll take a look at the next PR build, and if the tests don't run it shouldn't be a biggie to fix as long as we have the credentials, thanks for adding them!!

**Pull request merged**
