### PR TITLE
Updating english docs to indicate the presence of hosted public proxies

### LINKED ISSUE #1235: Can't build Athens locally
**Describe the bug**

Since we removed the vendor directory, the `Makefile` (and documentation) are wrong because they assume there is a vendor directory.

**Error Message**

Please see #1233 

**To Reproduce**

Run `make build-ver VERSION="0.4.0"`

**Expected behavior**

The Athens binary should build successfully

**Environment (please complete the following information):**

Please see https://github.com/gomods/athens/issues/1233

**Additional context**

The solution for this should close #1233

### PR DESCRIPTION
**Pull request by arschles**
**What is the problem I am trying to address?**

Various docs don't mention public managed proxies like gocenter.io or proxy.golang.org

**How is the fix applied?**

I added that :)

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #1235

### CODE REVIEW

**Comment by arschles** [comment]
@lopezator @LinuxSuRen would each of you mind helping here with the Chinese and Spanish translations of the docs pages? We can do them in a follow-up or whatever other way you prefer.

**Comment by LinuxSuRen** [comment]
@arpitgogia I'd be happy to do the Chinese translation work.

**Comment by arschles** [comment]
Thanks @LinuxSuRen !

**Comment by lopezator** [comment]
I've linked a commit with th required changes. Let me know if you need any changes/additions @arschles !

**Comment by arschles** [comment]
Thanks so much @lopezator

**Comment by arschles** [comment]
@rimusz did I do something wrong on the [Helm CI check](https://circleci.com/gh/gomods/athens/61?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)? I can't seem to find anything, but I don't know what to look for either ;)

**Comment by rimusz** [comment]
the install error `Error: release athens-proxy-5c9fm3m2ea failed: Service "athens-proxy-5c9fm3m2ea-athens-proxy" is invalid: spec.ports: Required value`

**Comment by arschles** [comment]
@rimusz that's weird - I didn't change the helm chart templates or defaults at all. Is it a flake maybe?

**Comment by arschles** [comment]
@rimusz I pulled in the changes that were in master (you suggested them in https://github.com/gomods/athens/pull/1246#issuecomment-496507480) and this passes the helm lint checks now 😄 

I'm gonna self-merge since these docs are important for newcomers to see.

**Comment by arschles** [comment]
And it's been double-approved 😄

**Comment by arschles** [comment]
@lopezator regarding https://github.com/gomods/athens/pull/1238#issuecomment-495106225, would you mind creating a pull request with that change (or did you do that already and I missed it)?

**Comment by lopezator** [comment]
@arschles done! :)

**Pull request merged**
