### PR TITLE
update redigo

### PR DESCRIPTION
**Pull request by komuw**
# what have you changed?
- replaced `github.com/garyburd/redigo` with  `github.com/gomodule/redigo`
- also updated `github.com/gocraft/work`

# why have you changed it?
- `garyburd/redigo` is archived and development has moved to `github.com/gomodule/redigo`
- updated `github.com/gocraft/work` since their newer version also uses `gomodule/redigo`
- fixes https://github.com/gomods/athens/issues/260

### CODE REVIEW

**Comment by komuw** [comment]
this is ready for review,  I think.

**Comment by robjloranger** [comment]
There seems to be an issue between the dependencies `gomodule/redigo` and `gocraft/work`. I ran `dep ensure` in your branch and got the following:
2018-07-14-095027_1600x328_scrot

**Comment by komuw** [comment]
@robjloranger thanks I'll work on fixing that.

speaking of which; maybe we should add `dep ensure` to  https://github.com/gomods/athens/blob/master/.travis.yml

**Comment by michalpristas** [comment]
on problem reported by rob. maybe lets try removing gedigo/redis from gopkg or remove restriction on version. not gocraft/work nor gobuffalo/gocraft-work-adapter has any restrictions on that

**Comment by robjloranger** [comment]
fyi, script for travis ci inbound

**Comment by komuw** [comment]
@robjloranger @michalpristas 
take another look.

**Pull request merged**
