### PR TITLE
add golint (and its deps) to mod and sum files

### PR DESCRIPTION
**Pull request by penDerGraft**
Based on discussion in #646 it seems like these deps got excluded from these files somehow and are being introduced during the build steps. I think adding these should fix the build. 

I'm still new to modules so feel free to close the PR if this is unexpected behavior.

### CODE REVIEW

**Comment by penDerGraft** [comment]
At second glance, I think there are additional build errors. May still want to have this PR though since the files are getting modified locally as well.

**Comment by manugupt1** [comment]
I have a couple of questions

1. Did you not get checksum mismatch error?
https://github.com/gobuffalo/suite/issues/13

I suspect this bug is related to the proxy only though.

2.  Should we not update the vendor folder if we are adding and we have a vendor folder?

**Comment by penDerGraft** [comment]
Thanks for the feedback! @manugupt1 Yep, running into that now. Going to dig into this to see if that is resolvable.

**Comment by penDerGraft** [comment]
Closing since #674 seems to solve the same issue.

**Pull request closed without merging**
