### PR TITLE
Added check sshGitServer and gitConfig for creating volumeMounts

### LINKED ISSUE #1367: Deployment to kubernets
In [this condition](https://github.com/gomods/athens/blob/master/charts/athens-proxy/templates/deployment.yaml#L146) missed the values for `sshGitServers` ([there](https://github.com/gomods/athens/blob/master/charts/athens-proxy/templates/deployment.yaml#L163))

```
{{- if or (eq .Values.storage.type "disk") .Values.upstreamProxy.enabled .Values.netrc.enabled }}
   volumeMounts:
{{- end }}
```
when I tried install to helm, I got an error:
```
$ helm install --namespace kube-public -f athens.yaml --set storage.mongo.url=mongodb://mongo.default.svc.cluster.local:27017 -n athens gomods/athens-proxy
Error: release athens failed: Deployment.apps "athens-athens-proxy" is invalid: [spec.template.spec.containers[0].ports[1].name: Invalid value: "ssh-git-servers-config": must be no more than 15 characters, spec.template.spec.containers[0].ports[1].containerPort: Required value, spec.template.spec.containers[0].ports[2].name: Invalid value: "ssh-git-servers-config": must be no more than 15 characters, spec.template.spec.containers[0].ports[2].containerPort: Required value, spec.template.spec.containers[0].ports[3].containerPort: Required value]
```
I disabled `upstreamProxy`, `netrc` and used `type: mongo` in storage.

### PR DESCRIPTION
**Pull request by sah4ez**
Fixes #1367

### CODE REVIEW

**Comment by rimusz** [comment]
yup, any change to the chart, needs char’s version bump

**Comment by sah4ez** [comment]
Oh, sure. I'm forget about version. I fixed it. @arschles

**Comment by arschles** [comment]
@sah4ez there's a conflict in `Chart.yaml` - it's a single line. Do you mind if I resolve it on my side? GitHub has a little tool to let me do it. If you'd like to do it, absolutely no worries!

**Comment by sah4ez** [comment]
@arschles I fixed conflicts.

**Comment by arschles** [comment]
@sah4ez I'm so sorry I didn't get back to you for 17 days! There is the same chart version conflict on `Chart.yaml` that I can fix on my end, but it will modify your fork. Can you let me know if that is ok?

**Comment by sah4ez** [comment]
@arschles I updated this PR.

**Comment by arschles** [comment]
@sah4ez can you update the chart version _one_ more time to 0.3.7? Our CI keeps requiring that. When you're done with that, can you then send me a message to `@arschles` on the Gophers Slack, so that I merge it quickly for you? I have a hard time keeping up with all the GitHub notifications

**Pull request merged**
