### PR TITLE
Add support for Go Modules

### LINKED ISSUE #462: add go.mod file
As athens is intended for the world of Go modules, it would seem reasonable to add a go.mod file so that it can be managed in that way.

FWIW, here's a working go.mod file as of commit 051f3884e1fcd5df3d07a7199e9df40bb29702d0.
It required a little bit of tweaking despite being initially generated from Gopkg.lock - not sure why.

	module github.com/gomods/athens
	
	require (
		cloud.google.com/go v0.23.0
		github.com/Azure/azure-pipeline-go v0.0.0-20180607212504-7571e8eb0876 // indirect
		github.com/Azure/azure-storage-blob-go v0.0.0-20180507052152-66ba96e49ebb
		github.com/BurntSushi/toml v0.3.0 // indirect
		github.com/aws/aws-sdk-go v1.14.27
		github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973 // indirect
		github.com/bketelsen/buffet v0.0.0-20180802220535-2959027395a6
		github.com/codahale/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd // indirect
		github.com/codegangsta/negroni v0.3.0 // indirect
		github.com/dgrijalva/jwt-go v0.0.0-20180308231308-06ea1031745c // indirect
		github.com/dustin/go-humanize v0.0.0-20180713052910-9f541cc9db5d // indirect
		github.com/fatih/color v1.7.0
		github.com/globalsign/mgo v0.0.0-20180615134936-113d3961e731
		github.com/go-ini/ini v1.38.1 // indirect
		github.com/gobuffalo/buffalo v0.11.1
		github.com/gobuffalo/envy v1.6.3
		github.com/gobuffalo/gocraft-work-adapter v0.0.0-20180714213200-7d6504f1dffe
		github.com/gobuffalo/packr v1.13.1
		github.com/gobuffalo/pop v0.0.0-20180810203029-9f8bf0c11920
		github.com/gobuffalo/suite v2.1.2+incompatible
		github.com/gobuffalo/uuid v2.0.0+incompatible
		github.com/gobuffalo/validate v2.0.0+incompatible
		github.com/gobuffalo/x v0.0.0-20180117215853-11ca13c05abd // indirect
		github.com/gocraft/work v0.5.1
		github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b // indirect
		github.com/golang/protobuf v1.1.0 // indirect
		github.com/gomodule/redigo v2.0.0+incompatible
		github.com/google/go-cmp v0.2.0 // indirect
		github.com/googleapis/gax-go v2.0.0+incompatible // indirect
		github.com/gopherjs/gopherjs v0.0.0-20180628210949-0892b62f0d9f // indirect
		github.com/gorilla/websocket v1.2.0 // indirect
		github.com/hashicorp/errwrap v0.0.0-20180715044906-d6c0cd880357 // indirect
		github.com/hashicorp/go-multierror v0.0.0-20180715045037-12f8a7e29b82
		github.com/hpcloud/tail v1.0.0 // indirect
		github.com/jmespath/go-jmespath v0.0.0-20160202185014-0b12d6b521d8 // indirect
		github.com/jtolds/gls v4.2.1+incompatible // indirect
		github.com/kr/pretty v0.1.0 // indirect
		github.com/markbates/deplist v0.0.0-20170926152145-5ae023fef618 // indirect
		github.com/markbates/goth v1.45.7
		github.com/markbates/grift v1.0.1
		github.com/markbates/refresh v1.4.1 // indirect
		github.com/markbates/sigtx v1.0.0 // indirect
		github.com/markbates/validate v1.0.0 // indirect
		github.com/markbates/willie v1.0.4 // indirect
		github.com/matttproud/golang_protobuf_extensions v1.0.1 // indirect
		github.com/minio/minio-go v6.0.5+incompatible
		github.com/mitchellh/go-homedir v0.0.0-20180801233206-58046073cbff // indirect
		github.com/monoculum/formam v0.0.0-20170814190438-f25191ae7744 // indirect
		github.com/nicksnyder/go-i18n v1.10.0 // indirect
		github.com/onsi/ginkgo v1.6.0 // indirect
		github.com/onsi/gomega v1.4.1 // indirect
		github.com/opentracing/opentracing-go v1.0.2
		github.com/pelletier/go-toml v1.2.0 // indirect
		github.com/pkg/errors v0.8.0
		github.com/prometheus/client_golang v0.8.0 // indirect
		github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910 // indirect
		github.com/prometheus/common v0.0.0-20180518154759-7600349dcfe1 // indirect
		github.com/prometheus/procfs v0.0.0-20180705121852-ae68e2d4c00f // indirect
		github.com/robfig/cron v0.0.0-20180505203441-b41be1df6967 // indirect
		github.com/rs/cors v1.4.0
		github.com/russross/blackfriday v1.5.1 // indirect
		github.com/sabhiram/go-gitignore v0.0.0-20180611051255-d3107576ba94
		github.com/satori/go.uuid v1.2.0 // indirect
		github.com/shurcooL/github_flavored_markdown v0.0.0-20180602233135-8913699a52e3 // indirect
		github.com/shurcooL/go v0.0.0-20180423040247-9e1955d9fb6e // indirect
		github.com/shurcooL/go-goon v0.0.0-20170922171312-37c2f522c041 // indirect
		github.com/sirupsen/logrus v1.0.5
		github.com/smartystreets/assertions v0.0.0-20180803164922-886ec427f6b9 // indirect
		github.com/smartystreets/goconvey v0.0.0-20180222194500-ef6db91d284a // indirect
		github.com/spf13/afero v1.1.1
		github.com/stretchr/objx v0.1.1 // indirect
		github.com/stretchr/testify v1.2.2
		github.com/technosophos/moniker v0.0.0-20180509230615-a5dbd03a2245
		github.com/uber-go/atomic v1.3.2 // indirect
		github.com/uber/jaeger-client-go v2.14.0+incompatible
		github.com/uber/jaeger-lib v1.5.0
		github.com/unrolled/secure v0.0.0-20180618144512-8287f3899c8e
		go.opencensus.io v0.14.0 // indirect
		go.uber.org/atomic v1.3.2 // indirect
		golang.org/x/crypto v0.0.0-20180808211826-de0752318171 // indirect
		golang.org/x/net v0.0.0-20180811021610-c39426892332 // indirect
		golang.org/x/oauth2 v0.0.0-20180620175406-ef147856a6dd // indirect
		golang.org/x/sys v0.0.0-20180810173357-98c5dad5d1a0 // indirect
		golang.org/x/text v0.3.0 // indirect
		google.golang.org/api v0.0.0-20180712151135-781db45e5b94
		google.golang.org/appengine v1.1.0 // indirect
		google.golang.org/genproto v0.0.0-20180709204101-e92b11657268 // indirect
		google.golang.org/grpc v1.13.0 // indirect
		gopkg.in/airbrake/gobrake.v2 v2.0.9 // indirect
		gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 // indirect
		gopkg.in/fsnotify.v1 v1.4.7 // indirect
		gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2 // indirect
		gopkg.in/go-playground/assert.v1 v1.2.1 // indirect
		gopkg.in/ini.v1 v1.38.1 // indirect
		gopkg.in/mail.v2 v2.0.0-20180609202316-c55e3fbae0e2 // indirect
		gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7 // indirect
	)

### PR DESCRIPTION
**Pull request by komuw**
# what
- I added support for Go modules

# why
- Go 1.11 is now available https://golang.org/dl/

# how
- I ran `go mod -init` which used the existing `Gopkg.lock` file to create a `go.mod` file
- go mod -init didn't however add `gobuffalo/plus` which I had to add manually via; `go get github.com/gobuffalo/plush@v3.7.7`

Fixes #462

### CODE REVIEW

**Comment by komuw** [comment]
This can be held until Go 1.11 is released. 
I'll try and keep this PR updated - in the meanwhile - with any changes that may be made in `Gopkg.toml`/`Gopkg.lock`

**Comment by tbpg** [comment]
Should this delete `Gopkg.*`? The vendor directory can be kept checked in (with `go mod -vendor`) until Go 1.11 is required to build.

**Comment by arschles** [comment]
@tbpg good point. I would like to minimize disruption to the project and stick with `dep` to manage our vendor directory, until Go 1.11 is out. At that point, I am ok with removing the dep files and using go modules!

**Comment by arschles** [comment]
@tbpg @komuw are you both ok with merging this now? in a follow-up we can add docs indicating that we use `dep` for now until Go 1.11 comes out

**Comment by komuw** [comment]
> Should this delete Gopkg.*
@tbpg  I intend to do a follow up PR that deletes the Gopkg.* and vendor/ directory. 

> are you both ok with merging this now?
@arschles I think we should await Go 1.11 

I do intend to send another PR that will delete  Gopkg.* and vendor/ directory while at the same time adding a note on the README that we require a Go version that is compatible with modules. 

Both that and this PR should, I think, be put on hold until Go 1.11. 
I'll continue updating the two PR's with any changes that may be added to the Gopkg.lock file in the intervening period.

**Comment by tbpg** [comment]
Sounds good to me - I'm happy either way.

**Comment by arschles** [comment]
@komuw regarding https://github.com/gomods/athens/pull/371#issuecomment-409491159:

That all sounds amazing. Thank you for keeping things up to date. Now that 1.11 beta3 is out, 🤞 for a stable release soon!

**Comment by robjloranger** [comment]
for ref: https://github.com/gomods/athens/issues/462#issuecomment-412549100
Thanks, @rogpeppe

**Comment by komuw** [comment]
@arschles @robjloranger 
this PR is now ready, I have re-ran with the just released Go1.11 and also ran `go mod tidy`

**Pull request merged**
