### PR TITLE
Add support for Sail development environments

### PR DESCRIPTION
**Pull request by brainflake**
This will make it easy for new contributors to build and run the proxy locally using [Sail](https://sail.dev). The open issue for this is #1237 

## Overview

Sail aims to provide a turn key, immutable development environment for projects using it. To use it you need to install the CLI available at [sail.dev](https://sail.dev) and run `sail run gomods/athens`.

## Configuration

Configuration is done through a Dockerfile at `.sail/Dockerfile`. The command will use this to spin up a container the is preconfigured for a development environment. The base image includes [code-server](https://github.com/cdr/code-server) to enable a 'remote' development environment for VS Code on the container, accessible in your browser.

## Current status

`make` targets can be run from the VS Code console in the browser. Currently most of the non-docker targets work: `make build`, `make run`, `make test-unit`, etc. The unit tests are currently failing for me (it seems related to minio?).

### CODE REVIEW

**Comment by arschles** [comment]
@brainflake looks really cool. Do you know if there is a way to tell the sail CLI to use a different docker socket? I couldn't find one on the sail docs site.

**Comment by arschles** [comment]
And by the way, thanks for doing this!

**Comment by brainflake** [comment]
Hmm, I'm not sure to tell you the truth @arschles . Are you referring to the `EXPOSE` statement? I added that for the proxy, so when someone does a `make run` in the terminal inside sail they can access it from their localhost. Although now that I'm looking at it it doesn't seem to be working...

**Comment by arschles** [comment]
@brainflake sorry for the delay. I was referring to having sail talk to a different docker host on my machine, because I was trying to test with Docker for Mac and iirc it doesn't use the domain socket that's standard on most linux systems. did the same thing not work for you too?

**Comment by brainflake** [comment]
Ah, I see @arschles. So I was testing w/ Docker Desktop for Mac, which does use the standard domain socket at `/var/run/docker.sock` (although I think earlier versions for Mac use docker-machine, which uses a TCP socket).

As far as I can tell, sail will use the same configuration that the docker CLI uses, so it may be possible to point it to elsewhere using `DOCKER_HOST`, `DOCKER_MACHINE_NAME`, etc.

**Comment by brainflake** [comment]
Yeah after poking around a bit, looks like this is the entrypoint https://github.com/cdr/sail/blob/master/hat_builder.go#L35, which eventually calls https://github.com/moby/moby/blob/master/client/options.go#L19

So I think the those standard env vars should be respected

**Comment by arschles** [comment]
@brainflake There's a tiny conflict in `DEVELOPMENT.md`. Can you let me know if you'd like me to fix it (I can do it from the GitHub UI, but I don't want to commit directly to your `master` branch w/o your permission)?

**Comment by brainflake** [comment]
@arschles I just went ahead and merged the latest master into my branch so I think it should be good, but definitely don't hesitate if need be

**Pull request merged**
