### PR TITLE
Allow using existing service accounts

### PR DESCRIPTION
**Pull request by bnrjee**
## What is the problem I am trying to address?

Describe the issue you have been trying to solve.
Right now, there is no way to use existing service accounts to deploy athens using helm chart. It always tries to create a new one. But the requirement here is to use a service account that has already been created.
## How is the fix applied?

Mention briefly how you have applied the fix.
Tested with dry-run and on kubernetes cluster. With this change, athens can use an exiting service account.
## What GitHub issue(s) does this PR fix or close?

Fixes #

### CODE REVIEW

**Comment by bnrjee** [comment]
@arschles,
Would it be possible for you to take a look?

**Comment by arschles** [comment]
@bnrjee yes, I will look today ASAP

**Review by arschles — CHANGES_REQUESTED** [review]
@bnrjee don't you need to change the serviceAccount parameter in the [deployment.yaml](https://github.com/gomods/athens/blob/2428d133b7cb39c552d87b72563528418030e009/charts/athens-proxy/templates/deployment.yaml#L37) file and parameterize the name?

**Comment by bnrjee** [comment]
> @bnrjee don't you need to change the serviceAccount parameter in the [deployment.yaml](https://github.com/gomods/athens/blob/2428d133b7cb39c552d87b72563528418030e009/charts/athens-proxy/templates/deployment.yaml#L37) file and parameterize the name?

With the existing code(https://github.com/gomods/athens/pull/1672), a service account does get created and used. This PR will make sure, we will use the existing SAs and not create one. So, that kind of solves the problem.

**Comment by bnrjee** [comment]
> > @bnrjee don't you need to change the serviceAccount parameter in the [deployment.yaml](https://github.com/gomods/athens/blob/2428d133b7cb39c552d87b72563528418030e009/charts/athens-proxy/templates/deployment.yaml#L37) file and parameterize the name?
> 
> With the existing code(#1672), a service account does get created and used. This PR intends to make sure that we will be able to use the existing SAs and not create one. So, that solves the problem we are facing.

@arschles , Would it be possible for you to take a took, based on my update?

**Comment by abhay-krishna** [comment]
@arschles Is it possible to take a look at this and let us know your thoughts? Right now, we use a fork with the change that this PR adds. It would be helpful to have this feature in the upstream Athens so that we can remove forks and use charts directly from `gomods/athens`.

**Comment by arschles** [comment]
@abhay-krishna yup, I'll take a look tomorrow - sorry for the long delay

**Review by arschles — APPROVED** [review]
@bnrjee this is great. sorry for the delay! 🚀

**Comment by arschles** [comment]
@abhay-krishna @bnrjee you'll likely need to wait until we release a new version of Athens to take advantage of the helm chart changes. I'll be doing a release this week 👍

**Comment by bnrjee** [comment]
Hi @arschles,
Please let us know, when can we expect a new release with these new changes.

**Pull request merged**
