### PR TITLE
No conflicts

### LINKED ISSUE #273: Add build step to prevent merging conflicts
conflicts = the artifacts marking the conflicts. ie:
```
<<<<<< HEAD
```

A grep in bash should do the trick, like `^[<>=]{7}` would check for lines beginning with any of the `<<<<<<<`, `=======`, `>>>>>>>`

This way the build would fail when these are hiding somewhere in a toml or other 'diff collapsed by default' file.

### PR DESCRIPTION
**Pull request by robjloranger**
This new script returns exit code 1 when any files other than '*.go,go.mod,go,sum' contain merge conflict artifacts. `<<<<<<<HEAD`, `=======` or `>>>>>>>branch-name`.

It skips the mentioned files as those will be caught during linting and dependency checks.

closes #273

### CODE REVIEW

**Comment by marpio** [comment]
Wouldn't the build fail anyway if .go files contain merge conflict artifacts? I guess this shouldn't compile.

**Comment by michalpristas** [comment]
@marpio this should check files like *.toml, *.yml and docs

**Comment by marpio** [comment]
Oh, I've missed the *.go exclude. :+1:

**Comment by robjloranger** [comment]
@arschles it's included in the `make verify` target which CI is using.

**Comment by arschles** [comment]
ohhhh, got it @robjloranger - looks great! I'm waiting on CI, then will merge

**Pull request merged**
