### PR TITLE
Redirect to upstream on not found error

### PR DESCRIPTION
**Pull request by michalpristas**
**What is the problem I am trying to address?**

We have upstream in place but we don't redirect to it.

**How is the fix applied?**

Introducing middleware which checks error returned and if is 404 it redirects to a configured upstream proxy. If upstream not defined it returns 

Doublechecking redirect URI for ""
once when registering callback, the second time (redundancy but it makes intention clear) in middleware itself 

Just found out that it
Fixes: #800

### CODE REVIEW

**Comment by marpio** [comment]
@michalpristas  Is it meant as a replacement for https://github.com/gomods/athens/blob/f53ab925034a5c42cbf77d1bd2c53e6fa671f69b/pkg/middleware/filter.go#L38-L39

**Comment by michalpristas** [comment]
@marpio not a replacement
the thing you linked says: redirect whatever, dont even check what you have here
this middleware says: check if we have it locally, if not let user check another proxy

use case is as follows:
you have a client clien does go get
it hits first level proxy this one cannot see for whatever reason the package on a VCS, maybe it can see only internal ones or VCS is down 
so it says try this proxy as my backup
client tries to connect to upstream proxy which knows about the package

**Comment by michalpristas** [comment]
one more point, this is a very minor thing and probably we don't even need it

**Comment by robjloranger** [comment]
@arschles, @michalpristas that is likely just from #899 which I am writing on a fix now.

**Comment by robjloranger** [comment]
FYI @michalpristas I updated the branch to include the latest changes that fix the failing build.

**Comment by michalpristas** [comment]
will try that @marwan-at-work 
I was offline for a while. hopefully, I will find time to get this right

**Comment by arschles** [comment]
@michalpristas @robjloranger @marwan-at-work @marpio seems like this is no longer needed, since we're synchronously filling storage with code from the VCS or upstream proxy. Do I have that right?

**Comment by manugupt1** [comment]
@michalpristas are you still on this?

**Comment by arschles** [comment]
@michalpristas can we close this?

**Comment by marpio** [comment]
@michalpristas closing for now. Feel free to re-open if you want to continue on that.

**Pull request closed without merging**
