### PR TITLE
introduce go private configuration

### LINKED ISSUE #1373: introduce GOPRIVATE configuration for private modules
**Is your feature request related to a problem? Please describe.**
In #1294 #1304 , athens introduce a config to download from upstream proxy,
a approach to indicates module paths that are not publicly available and disable proxy is needed

**Describe the solution you'd like**
The go env `GOPRIVATE` is what we want, we should introduce it as configuration also.

### PR DESCRIPTION
**Pull request by yittg**
**What is the problem I am trying to address?**

provide an approach to disable `GOPROXY` for some modules

**How is the fix applied?**

introduce `GOPRIVATE` configuration

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #1373

### CODE REVIEW

**Comment by yittg** [comment]
it's good to support all of module aware go env, also to extend download files, if there's a plan for these, i'll vote for it.
it may be also good to supplement directly for GOPROXY, it's a server setup configuration, maybe we need not cover all configure path, just for the essentials.

**Comment by yittg** [comment]
@marwan-at-work would we close this PR then, discuss in the original issue if needed?
cc @arschles .

**Comment by arschles** [comment]
@yittg @marwan-at-work my understanding was that the use case for this was to selectively turn _off_ a `GOPROXY` for a module or glob of modules when the `downloadURL` is set. Did I get that wrong?

Anyway, if that was the goal here, I agree we should put it into the download mode file, just because that's where we're putting most of our module-specific configuration.

**Comment by yittg** [comment]
@arschles Did you mean that we should extend the download file to support cache from upstream urls or only fetch from original repos. We discussed it in a previous Issue #1294 / PR #1304 before I mentioned in #1373. Maybe we should do more and deeper discuss about it.

**Comment by arschles** [comment]
>Did you mean that we should extend the download file to support cache from upstream urls or only fetch from original repos

@yittg yup! Do you see a problem with adding the support in the download file? Happy to discuss more, feel free to `@` me on slack and we can discuss there or talk verbally

**Pull request closed without merging**
