### PR TITLE
chore(chart): update ingress to support apiVersion networking.k8s.io/v1

### LINKED ISSUE #1761: Helm chart ingress not working on Kube 1.22+
The ingress API version used in the helm chart (v1beta) was deprecated a while back and removed in Kubernetes v1.22.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/

### PR DESCRIPTION
**Pull request by qiuyuzhou**
## What is the problem I am trying to address?

update helm chart ingress to add apiVersion `networking.k8s.io/v1` in order to work with k8s 1.22+

## What GitHub issue(s) does this PR fix or close?

Fixes #1761

### CODE REVIEW

**Comment by Confushion** [comment]
please don't use k8s version comparisons, but use API capabilities instead:

Not:
`{{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion -}}`
`{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}`

But:
`{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}`
`{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}`

It makes code a lot easier to read/maintain.

**Comment by manugupt1** [comment]
@qiuyuzhou I like relying on capabilities better; is it possible to make that change?

**Comment by qiuyuzhou** [comment]
@manugupt1 `semverCompare` has been replaced by `Capabilities` method.

The left `semverCompare` are for `ingressClassName` and `pathType` introduced in v1.18.

https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/

**Comment by manugupt1** [comment]
cc @arschles Can you review this; as you have more knowledge on helm than I do.
The PR looks decent to me.

**Review by arschles — APPROVED** [review]
This looks reasonable to me too

**Comment by arschles** [comment]
@manugupt1 is this OK to merge?

**Comment by manugupt1** [comment]
thanks for the contribution @qiuyuzhou. LGTM. I will merge this.

**Review by manugupt1 — APPROVED** [review]

**Comment by hypnoglow** [comment]
Thank you for this MR.

BTW this change is actually breaking due to `ingress.hosts` structure changed from array of strings to array of objects. So I would suggest to use `0.6.0` for chart version.

**Comment by manugupt1** [comment]
@hypnoglow Which k8s version is breaking for you?

**Comment by hypnoglow** [comment]
It is not about k8s version, it's about the change in the chart `values.yaml`.

Before:

```yaml
hosts:
- example.com
```

After:

```yaml
hosts:
- host: example.com
   paths:
   - path: /
      pathType: ImplementationSpecific
```

**Comment by manugupt1** [comment]
@hypnoglow do you have a change that works for you? Will you be able to open a PR for it. I think the issue is that hosts is not filled up; but if you open a PR; I can test your change and make sure to merge it.

**Pull request merged**
