### PR TITLE
Replace GO_ENV in proxy Dockerfile with config-docker.toml

### PR DESCRIPTION
**Pull request by davidpfarrell**
**What is the problem I am trying to address?**

Because the proxy Dockerfile adds `GO_ENV=production`, there is no way to override the setting via the config.

This prevents the user from being able to use the config to fully manage their installation.

It does occur to me that a hard-default to Production mode is what you were aiming for, but I think there's another option that is equally as useful (if not more-so).

**How is the fix applied?**

Removes the `ENV` statement from the proxy Docker file.

Adds a new, docker-specific config file, `config-docker.toml`, which defaults to `"production"` mode.

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Relates to Ticket #1435

I purposefully decided on `-docker.toml` (vs say, `-prod.toml`) as I think a docker-specific config will prove to be useful in that we may decide on more docker-specific defaults over time (in fact I'm working on another PR that might apply).

*SIDE-NOTE:* You'll notice I added a `chmod` statement to the Dockerfile.  Working on this exposed the fact that the permission check of the config file is performed BEFORE the env replacement step, meaning that you can currently be in production mode with non-conforming permissions.   I'm working on another PR for that and will submit it shortly.

### CODE REVIEW

**Comment by marwan-at-work** [comment]
Also, can you please open an issue and tag it here. Every PR should link to an issue so that we can track any pre and follow-up discussions. Thanks!

**Comment by ferryvg** [comment]
You can pass `GO_ENV` with `-e` flag in `docker run` command:
`docker run -e GO_ENV=development gomods/athens:latest`
Or in docker-compose.yml, etc...

**Comment by davidpfarrell** [comment]
> Also, can you please open an issue and tag it here. Every PR should link to an issue so that we can track any pre and follow-up discussions. Thanks!

Done !  Ticket #1435 created and referenced in the description.  Thanks for taking the time to reply !

**Comment by davidpfarrell** [comment]
> You can pass `GO_ENV` with `-e` flag in `docker run` command:
> `docker run -e GO_ENV=development gomods/athens:latest`
> Or in docker-compose.yml, etc...

Indeed you can - My concern is that you *MUST* do so in order to engage dev mode, as having a hard-coded environment variable baked into the Dockerfile makes the configuration file property essentially useless.

Thanks for chiming in - I have created ticket #1435 to further discussion on matter - Please feel free to share your thoughts there.

**Comment by davidpfarrell** [comment]
Closing this PR since #1443 (merged) solves in a better way.

**Pull request closed without merging**
