### PR TITLE
[CNAB bundle] add athens.dockerapp file

### PR DESCRIPTION
**Pull request by nunix**
This file is base for creating a CNAB bundle using `docker-app` command.
More information on how to build the CNAB bundle for athens here: https://medium.com/@hoxunn/docker-cnab-containers-needed-a-bundle-7bb8cf55ced2

The file currently contains only the `DEV` environment of Athens (based on the compose file).
Everything is working except the `datadog` container has it needs an API key: `DD_API_KEY`.

**What is the problem I am trying to address?**

Describe the issue you have been trying to solve.

**How is the fix applied?**

Mention briefly how you have applied the fix.

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #

### CODE REVIEW

**Comment by arschles** [comment]
@nunix I don't have the know-how to get set up and try this out. Do you mind adding some instructions to the OP so that we can try it out?

**Comment by arschles** [comment]
@nunix and I talked offline, he is going to add some testing instructions here when he's back from travel

**Comment by nunix** [comment]
ok, here we go (finally) and really sorry for the delay.
In a nutshell, here are the steps to test the `dev` cnab bundle:

1. Pre-requisites
- [Optional] Install [Docker](https://docs.docker.com/install/)
- [Optional] Download the `docker-compose` [binary](https://github.com/docker/compose/releases)
- Download the `docker-app` binary from [GitHub](https://github.com/docker/app/releases)
- Set the `DOCKER_HOST` environment variable (mandatory, other else there will be errors)
```
### Bash
export DOCKER_HOST=unix:///var/run/docker.sock

### Powershell
$env:DOCKER_HOST='npipe:////./pipe/docker_engine'
```

2. Create a `swarm` context
```
### Bash
docker-app context create swarm --description "swarm context" --default-stack-orchestrator=swarm --docker=host=unix:///var/run/docker.sock
docker-app context ls
```
image

```
### Powershell
docker-app.exe context create swarm --description "Athens swarm context" --default-stack-orchestrator=swarm --docker-host=npipe:////./pipe/docker_engine
docker-app.exe context ls
```
image

3. Install the bundle
```
docker-app install athens.dockerapp --name athens --target-context=swarm
docker-app status athens
```
image

4. Workarounds
if you get any errors, during the installation, try to render and/or use `docker-compose` :
```
### Ensure the variables are well rendered
docker-app render

### Deploy the application with compose
docker-app render | docker-compose -f - up
```

Test it and please let me know if you face any issues, I'm still learning it and will do my best to support you 💯

**Comment by robjloranger** [comment]
I tried to test this out but get errors, both my docker version and the most recent docker app standalone do not have `context` as a sub command. what version of docker do I need to test this?

**Comment by arschles** [comment]
@nunix would you be up for continuing with this PR? No pressure at all, just let us know ✌️:smile:

**Comment by nunix** [comment]
hi everyone, yes sorry for the huge delay, now that CNAB spec is v1, let me resume the work 👍

**Comment by arschles** [comment]
@nunix awesome! Welcome back and looking forward to it 😄

**Comment by arschles** [comment]
Closing this due to inactivity. @nunix if you're still interested, let us know and we're happy to come back to it!

**Pull request closed without merging**
