### PR TITLE
Feature mod aliases

### LINKED ISSUE #1315: could athens support mirror?
**Is your feature request related to a problem? Please describe.**
a simple way to replace in athens, not in go.mod
batch config in athens

**Describe the solution you'd like**
Mirrors = [
"golang.org/x/(.*) => github.com/golang/$1",
"google.golang.org/appengine => github.com/golang/appengine",
"google.golang.org/genproto => github.com/google/go-genproto",
"google.golang.org/grpc => github.com/grpc/grpc-go",
"google.golang.org/api => github.com/googleapis/google-api-go-client",
"cloud.google.com/go => github.com/googleapis/google-cloud-go",
]

**Describe alternatives you've considered**
if impl..ed many project just simple write go.mod file

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ferryvg**
**What is the problem I am trying to address?**
We need set source repo url for module

**How is the fix applied?**
Added new block to `download.hcl` and method like `Mode.Match`

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #1315, #1132, #1334

### CODE REVIEW

**Comment by ferryvg** [comment]
Will be updated tomorrow, because not working for 2+ versions of module

**Comment by ferryvg** [comment]
go.mod support `replace` directive
https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

**Comment by blueworrybear** [comment]
@ferryvg 
Hi, I'm looking forward to this **Alias** feature. Although, **Go** supports `replace`, it does not mean Alias is not useful.

For example, I cannot access some VCS repositories due to the firewall policy in my department. Although I can use either:

1. `go mod replace`
2. `git` `insteadof` configure
3. Other goproxy server (Unfortunately, sometimes it's not working)

It's more convenience to me if I could set some redirection via Athens. Especially I could help my colleagues to avoid the same painful environment setup when they want to use the same modules.

Therefore, please don't give up working on the feature 👍 

BTW, I would like to know what happened for 2+ version of module? As I know, `go mod` requests using `url/to/module/v2` to denote breaking update. However, it seems to me that alias those URL is not impossible. Could we just replace `v2` in `Alias` function?

**Comment by letian0805** [comment]
This feature is very useful! Why not merge it?

**Pull request closed without merging**
