### PR TITLE
Fix K8s service account usage

### PR DESCRIPTION
**Pull request by owenhaynes**
## What is the problem I am trying to address?

For the K8s service account to be used in the deployment, fix legacy resource,  and allow annotations on service account.

## How is the fix applied?

added the service account to the deployment

### CODE REVIEW

**Review by arschles — APPROVED** [review]
@owenhaynes this looks great. thanks for it :)

**Comment by arschles** [comment]
oops @owenhaynes the helm chart version needs an increase, then this is all good to go

**Comment by owenhaynes** [comment]
@arschles done

**Comment by gw0** [comment]
I have a feeling that everyone forgot about this PR?

**Comment by arschles** [comment]
Apologies, this PR fell off of my GitHub notifications. The CI failure on this PR looks to be a flake, so I've restarted it and if it passes, I will merge

**Pull request merged**
