### PR TITLE
Refer to a consistent minimum Go version

### PR DESCRIPTION
**Pull request by scottilee**
**What is the problem I am trying to address?**

Describe the issue you have been trying to solve.

> The docs refer to two different versions of Go and there should only be reference to one for consistency.

**How is the fix applied?**

Mention briefly how you have applied the fix.

> I searched the Athens repo for all mentions of Go 1.11 and Go 1.12 and changed them to refer to Go 1.11+. This was discussed with Aaron Schlesinger on Slack as Go 1.11 is the minimum version supported.

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #

> There is no associated issue.

### CODE REVIEW

**Comment by scottilee** [comment]
Let me know if I should just change the "1.11"s to "1.12" now and make a note somewhere about most things working with 1.11.

**Comment by arschles** [comment]
nah, I think it's ok for now

**Comment by arschles** [comment]
@scottilee I didn't put it together that https://github.com/gomods/athens/pull/1121 will mean we require Go 1.12. Can you update these documentation to `1.12+` after all? Sorry for confusing everything here...

**Comment by scottilee** [comment]
No problem, I just pushed the change. I left the "+" so that it's easier for future releases but if that's not the case or it looks weird since 1.12 is the latest release let me know and I can remove the "+" so that it's just "v1.12".

I don't know why those chart YAML files got pulled in...

**Pull request merged**
