### PR TITLE
chart: allow setting deployment resource requests/limits

### LINKED ISSUE #1179: Add CPU and memory resources section to helm chart
**Is your feature request related to a problem? Please describe.**

Current helm chart does not allow to set any resource requests or limitations. This can result in scheduling Athens on a Kubernetes node that does not have enough spare CPU and memory.

**Describe the solution you'd like**

Add resource section to values.yaml, similar to how it's done in stable helm charts:
https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L142
https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L162

### PR DESCRIPTION
**Pull request by glb**
**What is the problem I am trying to address?**

Add CPU and memory resources section to helm chart

**How is the fix applied?**

Added the required elements to the `values.yaml` and the deployment template.

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #1179.

### CODE REVIEW

**Comment by glb** [comment]
Sample pod after installing using the example values:

```
kubectl describe pod riotous-puma-athens-proxy-79976cd755-svhrw
Name:               riotous-puma-athens-proxy-79976cd755-svhrw
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               [redacted]
Start Time:         Mon, 27 May 2019 10:38:01 -0400
Labels:             app=riotous-puma-athens-proxy
                    chart=athens-proxy-0.2.5
                    pod-template-hash=79976cd755
                    release=riotous-puma
Annotations:        checksum/config: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
                    checksum/secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Status:             Running
IP:                 [redacted]
Controlled By:      ReplicaSet/riotous-puma-athens-proxy-79976cd755
Containers:
  riotous-puma-athens-proxy:
    Container ID:   docker://463157cd77e775032a462fbbb4418991b3236c4bd36ddc8f4443637fd25c3bf7
    Image:          docker.io/gomods/athens:v0.4.0
    Image ID:       docker-pullable://gomods/athens@sha256:6e3d91fb9336a62784f417f99d69f20a3dd6698d609617fdb7368e7976a17b7b
    Port:           3000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 27 May 2019 10:38:07 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  64Mi
    Requests:
      cpu:      100m
      memory:   64Mi
...
```

*Note:* In order to install, I had to delete `templates/service-account.yaml`; I was getting the following error: 

```
helm install .
Error: release flippant-horse failed: Service "flippant-horse-athens-proxy" is invalid: spec.ports: Required value
```

which appears to be caused by https://github.com/gomods/athens/pull/1218/files#diff-835840a08dc41e7e855e5ff8a2160e53R2 -- this manifest doesn't seem to be a valid `Service`.

**Comment by glb** [comment]
I'm not sure I understand the issue reported by `lint-install-charts`:

```
 ✖︎ athens-proxy => (version: "0.2.5", path: "charts/athens-proxy") > Chart version not ok. Needs a version bump!
```

Should I have bumped the chart version in this PR? That doesn't seem right...

**Comment by rimusz** [comment]
yes, a chart version needs a bump, as the chart got changed :)

**Comment by rimusz** [comment]
@glb and please remove the `templates/service-account.yaml` file in your PR, as it is causing only issues

**Comment by glb** [comment]
@arschles sure, I can update the docs, should have done that in the initial commit. 

Looking more closely, it appears that the pattern is that the`README.md` points off to details in `docs/content/install/install-on-kubernetes.md` -- does the content automatically get synced or is there a release process? I'm happy to follow that pattern, just want to make sure that I don't introduce a broken link.

**Comment by arschles** [comment]
@glb there's no automatic syncing actually, we should just put all the docs in one place and then point to it from the other place. For now, can you add the docs in `docs/content/install/install-on-kubernetes.md`? After we merge this, I'll do a follow-up to point to that URL from the chart README.md.

Also, I will do what @rimusz said in https://github.com/gomods/athens/pull/1246#issuecomment-496507480 in another PR, shortly, and get it merged. You'll then be able to merge that code into here and that build error should be fixed

**Comment by rimusz** [comment]
@arschles the `service account` fix is already in the master, no needs to remove that file :)

**Comment by arschles** [comment]
woohooo! thanks @rimusz

**Comment by glb** [comment]
Rebased to upversion the chart (again).

**Comment by arschles** [comment]
@glb sorry for the delay. Do you mind if I fix the conflicts in this PR (I can do it from the GitHub UI) and merge?

**Comment by glb** [comment]
@arschles go for it! Thanks!

**Comment by arschles** [comment]
@glb done. merging 💯 🚀 🎉 

And thank you for your first contribution! I hope you make a second .. and beyond 😄

**Pull request merged**
