### PR TITLE
Fix missing chart apiVersion

### PR DESCRIPTION
**Pull request by hypnoglow**
## What is the problem I am trying to address?

`apiVersion` field is Chart.yaml is required but missing for some reason.

## How is the fix applied?

Added `apiVersion: v1` to the Chart.yaml

### CODE REVIEW

**Comment by gw0** [comment]
I have a feeling that everyone forgot about this PR. I believe it would make sense to merge that in and also upgrade the Athens version to 0.10.0?

**Comment by arschles** [comment]
@gw0 haven't forgotten about it, just trying to work through the backlog of reviews. sorry about the delay!

**Review by arschles — CHANGES_REQUESTED** [review]
@hypnoglow can you increment the PATCH version number in the `Chart.yaml`? once that's done, this is ready to merge

**Review by arschles — APPROVED** [review]

**Comment by arschles** [comment]
thanks @hypnoglow !

**Pull request merged**
