### PR TITLE
fix flake on redis-sentinel by depending on redis container / step.

### PR DESCRIPTION
**Pull request by manugupt1**
## What is the problem I am trying to address?

Redis tests have flakes, this leads to a bad CI.

Describe the issue you have been trying to solve.

## How is the fix applied?

Redis tests have flakes, by using depends_on flag; I am trying to reduce these flakes.

I tested by force-pushing multiple commits.

## What GitHub issue(s) does this PR fix or close?

Fixes #

### CODE REVIEW

**Review by arschles — APPROVED** [review]
thanks a ton @manugupt1 !

**Comment by arschles** [comment]
@manugupt1 it looks like there's a new redis sentinel related error now: https://cloud.drone.io/gomods/athens/2308/1/9

**Comment by manugupt1** [comment]
thanks @arschles for review.

Adding dependencies did not seem to have fixed the issue; I will see what else can be done. This was what I was trying to fix.

**Comment by manugupt1** [comment]
@arschles do you think adding retries in this case would be acceptable

**Pull request merged**
