### PR TITLE
Propagate HOME env to go command execution

### LINKED ISSUE #959: Private repo using ssh not supported since git global config is ignored
I have a private gitlab repo that I use ssh instead of https to access. To make the `go` command aware of this, I add a configuration in my global git configuration file `$HOME/.gitconfig`:

`git config --global url."gitlab@privaterepo:".insteadOf "https://privaterepo/"`

Now `go get` from my private repo works like a charm.

When I use Athens as proxy, it calls `go mod download -json` and it fails since it still tries to access my private repo using https despite my config.

The reason for this is that Athens sets environment variables in: https://github.com/gomods/athens/blob/154c993c42c6dfd43a6adf60e543f5a98b468509/pkg/module/go_get_fetcher.go#L161-L182

And `HOME` isn't one of the variables that is passed on to the command. The result is that `git` cannot find the global configuration file, and all settings are ignored.

**Environment (please complete the following information):**
 - OS: Linux
 - Go version : 1.11
 - Buffalo Version : -
 - Proxy version : master
 - Storage (fs/mongodb/s3 etc.) : mem or disk

### PR DESCRIPTION
**Pull request by leitzler**
Add the ability to manually point out a git configuration file. This is needed to be able to use private repositories that uses ssh instead of https, see #959 

There is also a `GIT_CONFIG` env but it seems like only `git config` uses that one:
https://github.com/git/git/blob/965798d1f2992a4bdadb81eba195a7d465b6454a/builtin/config.c#L601

Fixes #959

### CODE REVIEW

**Comment by robjloranger** [comment]
Is the env variable `HOME` available on all host architectures? I'm mostly wondering about windows.

We might need an OS switch for this one and point to `%UserProfile%` or similar.

**Comment by leitzler** [comment]
You might be right, I don't have access to any Windows machine to test. The implementation follows the environment variables in specified in [git-scm](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables). Wouldn't be surprised if Windows handles it in a special way.

**Comment by robjloranger** [comment]
You can use the variable `GIT_CONFIG` to point to a configuration file.

## GIT_CONFIG
```Take the configuration from the given file instead of .git/config. Using the "--global" option forces this to ~/.gitconfig. Using the "--system" option forces this to $(prefix)/etc/gitconfig```

**Comment by leitzler** [comment]
See original description. Feel free to try it yourself with `fetch` (and share what version of git you use if it works).

**Comment by leitzler** [comment]
Also, it wouldn’t enable more configuration than this PR. Since if HOME is passed on athens will be able to (automatically) use the specific users global configuration.

**Comment by leitzler** [comment]
Looks like the official git uses `HOME` even for Windows:

Opening the config file: https://github.com/git/git/blob/d166e6afe5f257217836ef24a73764eba390c58d/builtin/config.c#L627

Expanding `HOME`: https://github.com/git/git/blob/d166e6afe5f257217836ef24a73764eba390c58d/path.c#L719

**Comment by arschles** [comment]
@leitzler I think @robjloranger had a good idea [in slack](https://gophers.slack.com/archives/C9LRAQN8N/p1544053564163400) (copied here):

>Maybe we can add a test to see if the variable is found and we have the git config file?

That way we can always be sure that we're setting the `HOME` variable properly on windows and linux-ey flavors too

**Pull request merged**
