### PR TITLE
Update to go1.19

### PR DESCRIPTION
**Pull request by manugupt1**
Updating to go1.19. This will update canary images.

### CODE REVIEW

**Review by marwan-at-work — APPROVED** [review]
🙌🏼

**Review by arschles — APPROVED** [review]
🚀

**Comment by r-ashish** [comment]
I was going to work on upgrading to go 1.19 to address this: https://github.com/gomods/athens/issues/1797 but then came across this PR so just checking in to see why this wasn't merged? Any blockers? Do we need more changes to fix the failing builds?

**Comment by manugupt1** [comment]
Can you please take this PR as I do not have the bandwidth; happy to review

**Comment by r-ashish** [comment]
> Can you please take this PR as I do not have the bandwidth; happy to review

Sure! Marking this as draft for now, will let you know once it's ready for review.

**Comment by manugupt1** [comment]
Thanks; for go 1.19; I think a bit more work was required as tests were failing other reasons. I will close this one.
Really appreciate taking over.

**Pull request closed without merging**
