### PR TITLE
removing the home handler on olympus

### PR DESCRIPTION
**Pull request by arschles**
Related to #314, which removes the home handler on the proxy

### CODE REVIEW

**Comment by arschles** [comment]
Yep - just 404

**Comment by marpio** [comment]
@arschles can we also delte `./cmd/olympus/templates/olympus/index.html` now?

**Comment by arschles** [comment]
@marpio @robjloranger are you ok if I leave the template dir but just delete the `index.html`? I'm asking because the `application.html` and `_flash.html` are reusable and we might want to use them later on...

**Comment by bketelsen** [comment]
OK on deleting the handler, but this will be an actual HTML end point at some future point.

**Pull request merged**
