### PR TITLE
Removed -mod=vendor from Makefile and docs 

### LINKED ISSUE #1242: Remove -mod=vendor from source and docs
https://github.com/gomods/athens/pull/1231 removed the vendor directory but there are still some ` -mod=vendor` left in our Makefile and docs.

We should remove those and use GOPROXY=https://proxy.golang.org instead to build Athens.

### PR DESCRIPTION
**Pull request by penthaapatel**
Fixes #1242 Remove -mod=vendor from source and docs 
**How is the fix applied?**
Removed -mod=vendor from Makefile and docs

### CODE REVIEW

**Comment by penthaapatel** [comment]
> @penthaapatel so far so good! 
> 
> Can you make sure that `GOPROXY` is set to `https://proxy.golang.org` in all the places where you removed `-mod=vendor`?

@arschles Are the new changes correct? Please review. [https://github.com/gomods/athens/pull/1250/commits/d49bf2a4c83a158626f709003b01a02c11178160](url)

**Comment by arschles** [comment]
@penthaapatel almost there! I had just one more change I saw

**Comment by penthaapatel** [comment]
> @penthaapatel looks like the `build-ver` target in the `Makefile` still uses `-mod=vendor`. Can you change that to use `GOPROXY` instead?

I need more help on this. I had made the changes in Makefile. Are they incorrect? I noticed the `cmd/proxy/Dockerfile` and the `.sh` files in `scripts` directory still use `-mod=vendor`. Is that the reason why the tests show the `-mod=vendor` still in use?

**Comment by marwan-at-work** [comment]
@penthaapatel the Dockerfile is currently trusting the CI/CD (DroneCI) to create a vendor folder on the fly, but for now you can: 
1. Set `GOPROXY=https://proxy.golang.org` inside the Dockerfile and remove `-mod=vendor` 
2. Expose the GOPATH cache to the Dockerfile from the recently built DroneCI pipeline. 

I think option one is a lot easier for now, and option two can be another PR later.

**Comment by penthaapatel** [comment]
> @penthaapatel the Dockerfile is currently trusting the CI/CD (DroneCI) to create a vendor folder on the fly, but for now you can:
> 
> 1. Set `GOPROXY=https://proxy.golang.org` inside the Dockerfile and remove `-mod=vendor`
> 2. Expose the GOPATH cache to the Dockerfile from the recently built DroneCI pipeline.
> 
> I think option one is a lot easier for now, and option two can be another PR later.

@arschles @marwan-at-work I made the changes in Dockerfile. Please review.

**Comment by penthaapatel** [comment]
> @penthaapatel thanks for sticking with this! I'm gonna merge this now.   :shipit:
> 
> Like @marwan-at-work said, would you be up for adding functionality in another PR to allow someone to set their own `GORPOXY`?

@arschles Sure, I can give it a try! :smile:

**Comment by penthaapatel** [comment]
> @penthaapatel thanks for sticking with this! I'm gonna merge this now.   :shipit:
> 
> Like @marwan-at-work said, would you be up for adding functionality in another PR to allow someone to set their own `GORPOXY`?

@arschles Sure, I can give it a try! :smile: I would need more guidance on it though.

**Pull request merged**
