### PR TITLE
WIP: add in memory pointer registry

### PR DESCRIPTION
**Pull request by robjloranger**
Just using a map.

Not sure about my current placement, created a new package for in memory registry. Declared an error for when a deployment is not present in the registry inside the eventlog pkg.

### CODE REVIEW

**Comment by marpio** [comment]
I'm not sure this one is needed. We get this one for free if we implement the file system driver just like for the proxy storage. What do you think @arschles @michalpristas

**Comment by robjloranger** [comment]
Ok, no problem. So we only need the FS implementation, nothing specific to in memory?

**Comment by marpio** [comment]
@robjloranger the FS driver will accept `afero.Fs` as a parameter and we can provide in memory file system like this `afero.NewMemMapFs()`

**Comment by michalpristas** [comment]
for reference

https://github.com/gomods/athens/blob/8ceda38ad702b86ae9cb45090273e2e22fb14cbe/pkg/gomod/file/parser.go#L9-L12

**Comment by robjloranger** [comment]
I'm not sure I'm following. I was going off #146 which mentioned both fs and in memory. Just a couple questions to clear me up :smile: 

Will there still be two separate implementations needed? (file, memory)

If so, are you saying for the in memory implementation to make use of the fs implementation internally?

**Comment by arschles** [comment]
@robjloranger when we chatted in Slack, I left out an important detail! If you use `afero.Fs` in your pointer implementation, you get two 🐦s with one one stone (memory and on-disk).

Answers to your questions below

>Will there still be two separate implementations needed? (file, memory)

The implementations are provided by [afero](https://godoc.org/github.com/spf13/afero). They include memory and a bunch of filesystem ones. Check out [here](https://godoc.org/github.com/spf13/afero#Fs) for the implementations.

>If so, are you saying for the in memory implementation to make use of the fs implementation internally?

afero's [memory mapped "filesystem" implementation](https://godoc.org/github.com/spf13/afero#NewMemMapFs) of `afero.Fs` gives you a "filesystem" backed by memory, so that'll do the trick. We also use this as one of the storage drivers in the proxy storage backend (it's used basically for tests only)

**Comment by robjloranger** [comment]
Awesome, I'll work on this later this weekend.

**Comment by robjloranger** [comment]
So I'm going to close this and start on the FS driver, which will in turn be usable as our in memory driver as well. :beers:

**Comment by arschles** [comment]
Rad, thanks!

**Pull request closed without merging**
