### PR TITLE
Add dependabot for automatic dependency update

### PR DESCRIPTION
**Pull request by manugupt1**
## What is the problem I am trying to address?

I am trying to update dependencies automatically using dependabot. This will help us remove update dependencies automatically.

Describe the issue you have been trying to solve.

## How is the fix applied?

Mention briefly how you have applied the fix.

## What GitHub issue(s) does this PR fix or close?

Fixes #

### CODE REVIEW

**Review by arschles — APPROVED** [review]

**Comment by arschles** [comment]
This seems good to me. @manugupt1 @marwan-at-work thoughts?

**Review by marwan-at-work — COMMENTED** [review]
LGTM, though I'd love to not blindly upgrade dependencies without looking at what changes they've introduced first.

**Comment by manugupt1** [comment]
Dependabot should only open PRs not merge automatically

**Comment by marwan-at-work** [comment]
For sure, the comment still applies 👍🏼

**Comment by arschles** [comment]
My experience with dependabot in [KEDA](https://github.com/kedacore/keda) is overall positive. The only negative is that it may open a nontrivial amount of PRs in a short period of time. Regardless, it never automerges any of them, someone has to go through and choose to either merge or close.

**Comment by marwan-at-work** [comment]
@arschles @manugupt1 my apologies if I miscommunicated, I'm definitely in favor of merging this PR. I just meant that when dependabot opens a PR with a go.mod update to a dependency, we should probably go look into the release notes and code of said dependency to do a sanity check before we merge the bot PR. 

Thanks!

**Comment by arschles** [comment]
got it, thanks for clarifying! I'm ok with merging this too. I restarted the build in hopes that it will not flake again

**Comment by arschles** [comment]
drone passed, all other CI is green. merging!

**Pull request merged**
